Модуль 8.6: пикер времени напоминания
internetova/flutter_places pull request #23
Opened 2021-02-15 17:56 UTC by internetova

Чего то я запуталась, надо часы или календарь вывести? Раз иконка календарь я календарь вывела

<img width="515" alt="Снимок экрана 2021-02-15 в 20 35 40" src="https://user-images.githubusercontent.com/39735343/107979415-92fe8800-6fcf-11eb-868b-502e17951c6f.png">
<img width="493" alt="Снимок экрана 2021-02-15 в 20 29 59" src="https://user-images.githubusercontent.com/39735343/107979444-a01b7700-6fcf-11eb-82f7-63ba7e113bd3.png">

И еще вопрос. У меня периодически зависает приложение. Не знаю что с этим делать
<img width="493" alt="Снимок экрана 2021-02-15 в 20 48 17" src="https://user-images.githubusercontent.com/39735343/107979560-cfca7f00-6fcf-11eb-8fa7-98489cd0d58f.png">

Практически каждые 2 дня.

В консоли пишет
F/crash_dump32(13904): crash_dump.cpp:474] failed to attach to thread 185: Permission denied
F/crash_dump32(15420): crash_dump.cpp:474] failed to attach to thread 185: Permission denied
W/sugina.places(11561): Reducing the number of considered missed Gc histogram windows from 122 to 100

Приходится удалять эмулятор и создавать его заново. Может подскажете что с этим делать 👀🤗.

Спасибо)

2021-02-16 10:02 UTC, artem-zaitsev requested changes
Необходим пикер времени. В остальном пока норм, но исправьте

2021-02-16 10:02 UTC, r3tam commented on lib/ui/screen/widgets/sight_card.dart
> +  Future<DateTime> _setReminder(BuildContext context) => showDatePicker(
Необходимы часы все же. Это выбор времени, а не даты.

2021-02-16 11:04 UTC, internetova commented on lib/ui/screen/widgets/sight_card.dart
> +  Future<DateTime> _setReminder(BuildContext context) => showDatePicker(
часы
![Снимок экрана 2021-02-16 в 14 01 35](https://user-images.githubusercontent.com/39735343/108054581-e5878500-705f-11eb-8d7f-5d050369ab4a.png)


![Снимок экрана 2021-02-16 в 14 01 12](https://user-images.githubusercontent.com/39735343/108054567-e15b6780-705f-11eb-8771-fd264ddf7f36.png)

2021-02-17 10:15 UTC, artem-zaitsev approved these changes
Про вопрос помню, пока думаем. Как будет решение, отвечу в личку.

2021-02-17 10:21 UTC, merged