15.1: shared preferences
internetova/flutter_places pull request #37
Opened 2021-05-16 16:41 UTC by internetova

2021-05-16 20:53 UTC, internetova commented
❓❓❓**Вопросы к следующему заданию. Не совсем понятна формулировка.**

**1. Сохранение истории поиска:**
_saveSearchRequest(place:Place) - сохранение поискового запроса с информацией достопримечательности_
_После ввода запроса сохранить место в базе_


❓Вопрос: Не совсем понятно что значит "сохранение поискового запроса с информацией достопримечательности", ведь поиск осуществляется при вводе символов и в результате могут отображаться много карточек на которые даже пользователь и не нажмёт. "После ввода запроса сохранить место в базе" - мне не понятно какие в результате сохранять места?

Сейчас реализовано как в дизайне - сохраняется история текстовых запросов по результатам которых пользователь кликнул. 

2. Экран Хочу посетить
"По нажатию на сердечко на экране "Хочу посетить" удаляйте карточку из базы." ❓❓Там нет кнопки сердечко! Кнопка только кнопка удалить. Надо полагать, что это описка?

2021-05-17 19:42 UTC, dkrutskikh requested changes

2021-05-17 19:42 UTC, dkrutskikh commented on lib/data/repository/local_settings_repository.dart
> +      await setTheme(isDark: !isDark);
@internetova похоже что тут ошибка.

если isDark - true, будет `await setTheme(isDark: true);`
если isDark - false, будет `await setTheme(isDark: !false);` что равнозначно `await setTheme(isDark: true);`

2021-05-17 19:42 UTC, dkrutskikh commented on lib/main.dart
> +          create: (context) => SettingsInteractor(),
@internetova зачем вам тут context ?

2021-05-17 19:42 UTC, dkrutskikh commented on lib/ui/screen/splash_screen.dart
> +  late Future<bool> _isInitialized;
@internetova не вижу где происходит инициализация

2021-05-17 20:22 UTC, internetova commented on lib/data/repository/local_settings_repository.dart
> +      await setTheme(isDark: !isDark);
Вы правы, это вообще лишний метод - при установке новой темы виджет итак перестроится без дополнительных переключателей🤓. Наверное на автомате сделала.

2021-05-17 20:44 UTC, internetova commented on lib/main.dart
> +          create: (context) => SettingsInteractor(),
Не нужен 😉пыталась стейт из блокбилдера в роутер передать чтобы сплэш скрин открыть уже с загруженными данными из хранилища (первый запуск приложения или нет) - не заработало. Думала, может где контекст ещё надо передать. Забыла убрать потом когда разобралась.

2021-05-17 22:47 UTC, internetova commented on lib/ui/screen/splash_screen.dart
> +  late Future<bool> _isInitialized;
Ну вот поэтому я задала вопрос в начале 🤓 а Вы не ответили

2021-05-18 18:43 UTC, artem-zaitsev commented
Да, типичный кейс сплеш экрана - разного рода проверки на шаге инициализации приложения.

2021-05-18 18:46 UTC, artem-zaitsev commented
1. Тут упрощенный сценарий кеширования поисковых запросов(точнее подсказок при вводе). По строке сохраняете результаты. При вводе при отсутствии Сети смотрите в БД. Если есть в БД, показываем, если нет - ошибка. Но в целом надо просто продемонстрировать работу с БД.
2. Да.

2021-05-18 18:52 UTC, artem-zaitsev requested changes
Стоит подправить работу с кубитом на сплеше и онбоардинге

2021-05-18 18:52 UTC, artem-zaitsev commented on lib/data/local_storage/SharedPreferencesStorage.dart
> +  _initPrefs() async {
почему dynamic? Это типичный void.

2021-05-18 18:52 UTC, artem-zaitsev commented on lib/main.dart
> +                      settingsAppState:
Синхронное получение данных - это не совсем по концепции блока/кубита. Все-таки мы подписываемся на стейт. По идее у Вас должна проходить инициализация внутри Splash. А Onboard должен быть внутри подписан так же на кубит.

2021-05-19 19:39 UTC, dkrutskikh commented on lib/ui/screen/splash_screen.dart
> +  late Future<bool> _isInitialized;
@internetova извиняюсь не заметил. Сейчас еще вопросы остались?

2021-05-20 06:36 UTC, dkrutskikh approved these changes

2021-05-22 10:47 UTC, internetova commented
На основе этой ветки сделана следующая - 15.3

2021-05-22 10:47 UTC, closed without merging